spring:
  application:
    name: api-rest-docker

  main:
    allow:
      circular:
        references: true
#    Configuracion webflux
#    web-application-type: reactive
#    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql
    username: appdemo
    password: mysql1234

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false

  redis:
    host: localhost
    port: 6379
    timeout: 2000

  messages:
    basename: messages

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

application:
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration: 3600000
      refresh-token:
        expiration: 3600000

management:
  health:
    redis:
      enabled: true

resilience4j.ratelimiter:
  configs:
    default:
      limitForPeriod: 1
      limitRefreshPeriod: 1s
      timeoutDuration: 100ms
    backendAConfig:
      limitForPeriod: 1
      limitRefreshPeriod: 2s
      timeoutDuration: 100ms
  instances:
    limitPaises:
      baseConfig: backendAConfig
    limitEstados:
      baseConfig: backendAConfig
    backendB:
      limitForPeriod: 10
      limitRefreshPeriod: 1m
      timeoutDuration: 100ms