Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,1,'AGUASCALIENTES',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,2,'BAJA CALIFORNIA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,3,'BAJA CALIFORNIA SUR',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,4,'CAMPECHE',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,5,'COAHUILA DE ZARAGOZA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,6,'COLIMA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,7,'CHIAPAS',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,8,'CHIHUAHUA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,9,'DISTRITO FEDERAL',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,10,'DURANGO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,11,'GUANAJUATO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,12,'GUERRERO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,13,'HIDALGO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,14,'JALISCO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,15,'MÉXICO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,16,'MICHOACÁN DE OCAMPO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,17,'MORELOS',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,18,'NAYARIT',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,19,'NUEVO LEÓN',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,20,'OAXACA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,21,'PUEBLA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,22,'QUERÉTARO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,23,'QUINTANA ROO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,24,'SAN LUIS POTOSÍ',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,25,'SINALOA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,26,'SONORA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,27,'TABASCO',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,28,'TAMAULIPAS',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,29,'TLAXCALA',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,30,'VERACRUZ DE IGNACIO DE LA LLAVE',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,31,'YUCATÁN',1,1,sysdate());
Insert into estados (id_pais,id_estado,estado,estatus,id_user,fecha) values (1,32,'ZACATECAS',1,1,sysdate());

commit;
