name: Build and Push Docker image to Docker Hub

on:
  push:
    branches:
      - main  # O la rama que desees utilizar

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código del repositorio
      - name: Checkout project sources
        uses: actions/checkout@v4

      # Paso 2: Configurar Gradle (instalar Gradle)
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"

      # Paso 3: Ejecutar Gradle para compilar el proyecto
      - name: Build with Gradle
        run: ./gradlew build

      # Paso 4: Configurar Docker Hub (login)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 5: Construir la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t marini89/api-rest-docker:latest .

      # Paso 6: Etiquetar la imagen Docker con el commit SHA
      - name: Tag Docker image with commit SHA
        run: |
          docker tag marini89/api-rest-docker:latest marini89/api-rest-docker:${{ github.sha }}

      # Paso 7: Subir la imagen Docker a Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push marini89/api-rest-docker:latest
          docker push marini89/api-rest-docker:${{ github.sha }}